# Generated by Django 4.2.18 on 2025-02-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('article_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True)),
                ('article', models.TextField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('procedure', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
