version: '3.9'

services:
  hostelmeals-web:
    build: .
    container_name: hostelmeals-web
#    ports: 
#      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - database:/app/database
  static:
    image: nginx:stable
    ports:
      - "8000:80"
    depends_on:
      - hostelmeals-web
    volumes:
      - static_volume:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  static_volume:
  database: