version: '3.9'

services:
  hostelmeals-web:
    build: .
    container_name: hostelmeals-web
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
  static:
    container_name: hostelmeals-proxy
    image: nginx:stable
    ports:
      - "8000:80"
    depends_on:
      - hostelmeals-web
    volumes:
      - static_volume:/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres
    container_name: hostelmeals-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  static_volume:
  database: